<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Calculated Amount</name>
  <uuid>93188a71-8e24-4149-ae5d-188686d6ac80</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Has Insurance' 
then
	set decision to 'Estimated Amount' * 0.8;
else set decision to 'Estimated Amount' * 0.2 ;  ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
