<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>52c0ab7e-7f5f-45ce-afb4-d37ecb7e4149</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 0 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
